//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public double Price { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int MemberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
