//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ShopPayments = new HashSet<ShopPayment>();
        }
    
        public int id { get; set; }
        public string ItemName { get; set; }
        public long ItemId { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemCount { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual ICollection<ShopPayment> ShopPayments { get; set; }
    }
}
