//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int id { get; set; }
        public int MemberId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> BodyFat { get; set; }
        public Nullable<decimal> Neck { get; set; }
        public Nullable<decimal> Shoulders { get; set; }
        public Nullable<decimal> LeftBicep { get; set; }
        public Nullable<decimal> LeftForearm { get; set; }
        public Nullable<decimal> RightBicep { get; set; }
        public Nullable<decimal> RightForearm { get; set; }
        public Nullable<decimal> Chest { get; set; }
        public Nullable<decimal> Waist { get; set; }
        public Nullable<decimal> Hips { get; set; }
        public Nullable<decimal> LeftThighs { get; set; }
        public Nullable<decimal> RightThighs { get; set; }
        public Nullable<decimal> LeftCalves { get; set; }
        public Nullable<decimal> RightCalves { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
